### ISSUE TITLE
.env is being fetched and displayed in network logs

### ISSUE THREAD

**Issue by facusantillo** [elementalconcept/env-bakery#15]
When implementing the lib in my angular project, I see that my sensitive information is displayed in the network logs because it's being downloaded as part of the bundle in the assets folder.

What should the implementation be here so we can avoid publicizing this information?

**Comment by Auxx** [comment]
Front-end applications are ALWAYS downloaded in full. You should NOT have any sensitive information inside. Your back-end should deal with that stuff.

**Comment by facusantillo** [comment]
There are some frameworks, like Nebular, where you need to store some information in the client.

This is the case for the SSO in Microsoft:

`@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    HttpClientModule,
    NbAuthModule.forRoot({
      strategies: [
        AzureADB2CAuthStrategy.setup({
          name: 'azure',
          clientId: 'bde728e2-2809-4ff1-bc9c-7fcb23800ebe',
          clientSecret: '',
          authorize: {
            endpoint: 'https://login.microsoftonline.com/01513fd2-16a0-453b-9fa0-c9089bfa023e/oauth2/authorize',
            responseType: 'id_token',
            scope: 'openid',
            redirectUri: 'https://akveo.github.io/nebular/example/azure/callback',
            params: {
              p: 'b2c_1_nebular',
            },
          },
          token: {
            class: AuthAzureToken,
          },
          redirect: {
            success: '/example/azure',
          },
        }),
      ],
    }),

    NbCardModule,
    NbLayoutModule,
    AzureRoutingModule,
  ],
  declarations: [
    AzureLoginComponent,
    AzureCallbackComponent,
  ],
  providers: [
    AzureADB2CAuthStrategy,
  ],
})`

As you can see in this example, in the client you need to store sensitive information like the clientId and token, which would change in different environments.

We can do a SSR implementation, but I thought that this library was solving the configuration management of such scenarios, like dotenvx does implementing the crypto layer

**Comment by Auxx** [comment]
There's nothing you can do about it. Your app runs INSIDE the user browser. So all the code and data it relies upon must be transmitted through HTTP one way or another. Encryption doesn't do anything in this scenario as it is also part of the same application and all encryption keys must be transmitted as well, so your users will have the ability to decrypt everything themselves.

The only way to protect the sensitive data is to have it on back-end and never send it to front-end.
